---
  # This is a workflow to generate the zip file and metadata.json for KiCAD PCM
  # https://gitlab.com/kicad/addons/metadata/-/merge_requests/14
  
  name: KiCAD client packaging
  on: # yamllint disable-line rule:truthy
    release:
      branches: main
      types:
        - published
    workflow_dispatch:

  jobs:
    create_archive:
      runs-on: self-hosted
      steps:
        - name: Get latest tag
          uses: oprypin/find-latest-tag@v1
          with:
            repository: Liangtie/kicad-mac-builder
            releases-only: true
          id: latest-release
  
        - name: Checkout repo
          uses: actions/checkout@v3

        # - name: Setup brew env
        #   run: ./ci/arm64-on-arm64/bootstrap-arm64-on-arm64.sh

        # - name: Build kicad dependency with brew
        #   run: WX_SKIP_DOXYGEN_VERSION_CHECK=1 ./build.py --arch arm64 --target setup-kicad-dependencies

        # - name: Cache brew pkgs
        #   uses: actions/cache@v3
        #   with:
        #     key: brew_caches
        #     restore-keys: brew_caches
        #     path: |
        #       ~/Library/Caches/Homebrew
        #       /opt/homebrew

        - name: Triggers a build
          run:  ./build.py --arch=arm64 --target package-kicad-unified --kicad-git-url  https://gitlab.com/Liangtie/kicad.git  --kicad-ref origin/dev --release-name test

        # - name: Cache kicad build
        #   uses: actions/cache@v3
        #   with:
        #     key: build_cache
        #     restore-keys: build_cache
        #     path: |
        #       ~/Library/Caches/Homebrew
        #       /opt/homebrew

        - name: Upload installer as asset to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ./build/dmg/kicad-unified-test.dmg
            asset_name: kicad-unified-${{ steps.latest-release.outputs.tag }}-test.dmg
            overwrite: true
            tag: ${{ steps.latest-release.outputs.tag }}
